---
description: "Learn more about: 'Catch' cannot appear after 'Finally' within a 'Try' statement"
title: "'Catch' cannot appear after 'Finally' within a 'Try' statement"
ms.date: 07/20/2015
f1_keywords: 
  - "vbc30379"
  - "bc30379"
helpviewer_keywords: 
  - "BC30379"
ms.assetid: 33d1278b-cf10-4c66-aaf8-08a4372f370b
---
# 'Catch' cannot appear after 'Finally' within a 'Try' statement

A `Catch` statement appears in the code after the `Finally` ending a `Try` statement block. `Catch` must appear within a `Try...Catch...Finally` statement block.  
  
 **Error ID:** BC30379  
  
## To correct this error  
  
1. Move the `Catch` statement to a more appropriate place in the code.  
  
## See also

- [Try...Catch...Finally Statement](../language-reference/statements/try-catch-finally-statement.md)
