---
description: "Learn more about: 'Catch' cannot appear outside a 'Try' statement"
title: "'Catch' cannot appear outside a 'Try' statement"
ms.date: 07/20/2015
f1_keywords: 
  - "bc30380"
  - "vbc30380"
helpviewer_keywords: 
  - "BC30380"
ms.assetid: 73ce950d-881f-4532-8024-40a4930abd32
---
# 'Catch' cannot appear outside a 'Try' statement

`Catch` must appear within a `Try...Catch...Finally` statement block. Either you have an unnecessary `Catch` statement in your `Try` block, or your `Catch` statement appears outside the bounds of its corresponding `Try` block.  
  
 **Error ID:** BC30380  
  
## To correct this error  
  
1. Delete the `Catch` statement if it is unnecessary, or place it within a `Try...Catch...Finally` statement block.  
  
## See also

- [Try...Catch...Finally Statement](../language-reference/statements/try-catch-finally-statement.md)
